# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'llm_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11llm_service.proto\x1a\x1cgoogle/protobuf/struct.proto\"\'\n\x10HandshakeRequest\x12\x13\n\x0bjson_config\x18\x01 \x01(\t\"A\n\x11HandshakeResponse\x12,\n\x0bjson_config\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"A\n\x0bTextRequest\x12\r\n\x05input\x18\x01 \x01(\t\x12\x12\n\nagent_name\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"<\n\x0cTextResponse\x12,\n\x0bjson_config\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"(\n\x12\x44\x65leteAgentRequest\x12\x12\n\nagent_name\x18\x01 \x01(\t\"C\n\x13\x44\x65leteAgentResponse\x12,\n\x0bjson_config\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2\xd4\x01\n\nLLMService\x12\x32\n\tHandshake\x12\x11.HandshakeRequest\x1a\x12.HandshakeResponse\x12+\n\x0cGenerateText\x12\x0c.TextRequest\x1a\r.TextResponse\x12+\n\nStreamText\x12\x0c.TextRequest\x1a\r.TextResponse0\x01\x12\x38\n\x0b\x44\x65leteAgent\x12\x13.DeleteAgentRequest\x1a\x14.DeleteAgentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HANDSHAKEREQUEST']._serialized_start=51
  _globals['_HANDSHAKEREQUEST']._serialized_end=90
  _globals['_HANDSHAKERESPONSE']._serialized_start=92
  _globals['_HANDSHAKERESPONSE']._serialized_end=157
  _globals['_TEXTREQUEST']._serialized_start=159
  _globals['_TEXTREQUEST']._serialized_end=224
  _globals['_TEXTRESPONSE']._serialized_start=226
  _globals['_TEXTRESPONSE']._serialized_end=286
  _globals['_DELETEAGENTREQUEST']._serialized_start=288
  _globals['_DELETEAGENTREQUEST']._serialized_end=328
  _globals['_DELETEAGENTRESPONSE']._serialized_start=330
  _globals['_DELETEAGENTRESPONSE']._serialized_end=397
  _globals['_LLMSERVICE']._serialized_start=400
  _globals['_LLMSERVICE']._serialized_end=612
# @@protoc_insertion_point(module_scope)
